alias pip="pip3"
alias python="python3"
alias pinst="pip install --upgrade"
alias pypy="pypy3"
alias ipython="ipython3"
alias myip="curl https://ipinfo.io/ip" 
alias vim="nvim"
alias bashconf="vim ~/.bash"
alias tmuxconf="vim ~/.config/tmux/tmux.conf"
alias vimconf="vim ~/.config/nvim"
alias gitconf="vim ~/.gitconfig"
alias fzf="fzf --preview 'bat --style numbers,changes --color=always {} | head -500'"
alias grep="rg --color=always"
alias reload="source ~/.bashrc"
alias sdcv="sdcv --color"
alias arena="~/archive/chess/arena/Arena_x86_64_linux"
alias stockfish="/home/arjun/archive/chess/stockfish"
alias mkalias="vim ~/.bash/aliases.sh"
alias mkfunction="vim ~/.bash/functions.sh"
alias srcpy="source env/bin/activate"
alias mkenv="python -m venv env"
alias ping="gping"
alias i3conf="vim ~/.config/i3/config"
alias diff="diff-so-fancy"
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias wezconf='vim ~/.config/wezterm/'
alias starconf='vim ~/.config/starship.toml'
